name: safety
description: "A Women's Safety Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.5.4'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: any
  flutter_local_notifications: ^19.2.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2

  # Firebase (latest compatible)
  firebase_core: ^3.13.0
  cloud_firestore: any
  firebase_auth: any
  firebase_messaging: ^15.2.5
  # Google
  google_sign_in: ^6.2.2
  # google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4

  # Location / Device
  geolocator: ^14.0.0
  location: ^8.0.0
  permission_handler: ^12.0.0+1
  shared_preferences: any
  contacts_service:
    git:
      url: https://github.com/hkhere/flutter_contacts.git
      ref: master
  sound_mode:
    git:
      url: https://github.com/chathurach/sound_mode.git
      ref: main

  # Voice / Audio
  record: ^6.0.0
  speech_to_text: any

  # App Meta
  rename_app: ^1.6.2
  rename: ^3.0.2

  # UI
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  url_launcher: ^6.1.14
  audioplayers: ^6.4.0
  path_provider: ^2.1.2
  provider: any
  flutter_sound: ^9.2.13
  sensors_plus: ^3.0.3
  flutter_volume_controller: ^1.0.0
  flutter_sms: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding3.png
    - assets/image.png
    - assets/onboarding1.png
    - assets/onboarding2.webp
